### ISSUE TITLE
Portal not working 

### ISSUE THREAD

**Issue by MadManPaddy** [quek04/The-Undergarden#122]
Built same dimensions as nether portal using both stone bricks and deep slate bricks.

**Comment by quek04** [comment]
going to need more info?

**Comment by quek04** [comment]
going to need more info?

**Comment by PatTheWizard** [comment]
I had this issue as well when i created the portal frame and made the catalyst i activated the portal. made sounds and everything, when i went into the portal it wouldnt do anything, id be standing there waiting to be take to the dimension but nothing happened

**Comment by quek04** [comment]
if you are on a server, a /reload and a server reboot might fix it. if you are on singleplayer, you need to make a new world... this is a vanilla bug

**Comment by EnergizedBlast** [comment]
Just wanted to post a solution I had, since the /reload (once and twice) and restart didn't work for me at all server side. For those wanting to use an existing world that was created _before_ adding the mod:

- Generate a new single player world with the mod already installed
- Locate your level.dat inside that new world save
- Using an NBT editor (I'm using NBTExplorer here) navigate to "Data > WorldGenSettings > dimensions > undergarden:undergarden"
- Copy the entire NBT entry
- Go to your server world's level.dat and paste the missing NBT entry inside the same location where it should be

![image](https://user-images.githubusercontent.com/40901561/158685940-9b06f561-ac5a-462a-b8e1-574c56ede2d8.png)

Doing this and restarting the server was all I needed to do, and this was also how I fixed another datapack based mod (Nullscape) which suffered the same issue of not populating into the forge dimension registry for some reason.
As always, **make sure to backup your world before doing this**; this at least worked for me and I hope this helps some other people out there!
