### ISSUE TITLE
[Bug - Crash] Incompatable with It Shall Not Tick Mod

### ISSUE THREAD

**Issue by Camawama** [quek04/The-Undergarden#159]
crashes when rendering undergarden:scintling

MC VERSION: 1.18.2
FORGE VERSION: 40.1.85

LOGS: https://pastebin.com/42WR05m3

**Comment by Camawama** [comment]
https://crashy.net/KgdxSSDu4KpomZvQZW3L

**Comment by Fooshcookie** [comment]
Before anything, I will say, there is a very, very slim chance Quek will go back to anything with 1.18.2, unless it is absolutely game breaking on his end. So, I can't make promises this will be fixed.

It appears the mod ISNT (It Shall Not Tick) has, or claims to on the CurseForge page, a config for excluding/blacklisting mobs. While, I have never used the mod myself, typically messing with configs is the best way to get things to work with mod packs. 

If you have not done it yet, find that config file, and add 'undergarden:scintling' to the exclusions/blacklist, and try again. From there, let us know if the issue persists or not, and I can see if I can convince Quek to look into the issue to see if it's on our end.

Again, no promises, as 1.19 and future updates is always the focus.

**Comment by GizmoTheMoonPig** [comment]
this was ultimately a problem with Open Parties and Claims. The issue was fixed on their github: https://github.com/thexaero/open-parties-and-claims/commit/d2cf74fc7e2dc9363635b11a9db20d78c0905d83. Make sure to update the mod when it releases an update. Make sure you let the issue you opened for ISNT know as well since they had absolutely no part in this

**Comment by Camawama** [comment]
> 

Thank you for this. I never would have known...
