### ISSUE TITLE
Active portal doesn't work

### ISSUE THREAD

**Issue by AlscarB** [quek04/The-Undergarden#189]
Can activate the portal fine, however when walking inside of it/standing inside of it. Nothing happens, every other dimensional portal works except the Undergarden. This is on the RAD2 pack specifically but the error occurs separate to the pack as well
![image](https://github.com/quek04/The-Undergarden/assets/54087010/111d5cde-4442-440c-a81b-51c5aa5a0585)
![image](https://github.com/quek04/The-Undergarden/assets/54087010/64029ef3-67f9-4f4c-86a9-d752fe1fa85b)

_Originally posted by @AlscarB in https://github.com/quek04/The-Undergarden/issues/15#issuecomment-1982357289_

**Comment by Korubiiii** [comment]
bump. Also having this issue on my friends 1.20.1 server. Very odd that this issue is common enough to have multiple posts about it and somehow nobody knows why or whats going on smh.

**Comment by Fooshcookie** [comment]
Version (mod, game, loader), and logs. We can't do anything with just screenshots.

**Comment by AlscarB** [comment]
It's clear that based on the responses themselves, on top of the delay, with people facing issues you don't care enough to even try, I gave up on this mod entirely.

I understand certain fixes and attempts would require specific data, but an attempt to even pretend to care would've been sufficient, maybe next person that has this issue at least act like you're giving suggestions/assistance while gathering data from those affected.

**Comment by GizmoTheMoonPig** [comment]
Perhaps consider next time that we have lives and cant attend to every issue right when its opened. You're also using an insanely outdated version of the mod which hasn't been supported in years. Your hostility is not appreciated (nor is giving snark on other tickets)
Dimensions in 1.16 dont properly load sometimes. This is beyond our control but theres a possible fix you can do. Run the /reload command twice and restart the world, should fix your problem.

**Comment by AlscarB** [comment]
Bro this issue has been around for 4 years lmao, it's superceded versions. When the issue was posted it was the most up to date version anyway.
No hostility intended, just making sure you're aware on how you could improve and informing those who are still having this unfixed issue.

Also so you're aware and can get to investigating your issue, from memory (since I stopped using your mod when I played) every single other dimension mod used work (concurrently) without alteration or issue, accessing the dimension was possible through commands so it was just the portal that was broken, so that's where you should start looking to begin your tests

**Comment by Fooshcookie** [comment]
Drop the attitude. 

For the longest time nobody knew what the problem was. We figured it out after taking over a year break from everything. As all of us have been busy, burnt and generally tired. 

After getting some negativity out of the mod team, we are working on doing better. Either provide the logs or move along. We are working to solve issues, as it stands.

**Comment by AlscarB** [comment]
👍

**Comment by Korubiiii** [comment]
> Drop the attitude.
> 
> For the longest time nobody knew what the problem was. We figured it out after taking over a year break from everything. As all of us have been busy, burnt and generally tired.
> 
> After getting some negativity out of the mod team, we are working on doing better. Either provide the logs or move along. We are working to solve issues, as it stands.

He was right, and you spent all your time talking about his "attitude" oof. Also, while I agree logs are important, this bug is common enough to where there's no way you haven't seen it before, Idk why any of you are acting surprised tbh.

**Comment by quek04** [comment]
pointless argument about problem I've never encountered is pointless

**Comment by Fooshcookie** [comment]
> > Drop the attitude.
> > 
> > For the longest time nobody knew what the problem was. We figured it out after taking over a year break from everything. As all of us have been busy, burnt and generally tired.
> > 
> > After getting some negativity out of the mod team, we are working on doing better. Either provide the logs or move along. We are working to solve issues, as it stands.
> 
> He was right, and you spent all your time talking about his "attitude" oof. Also, while I agree logs are important, this bug is common enough to where there's no way you haven't seen it before, Idk why any of you are acting surprised tbh.

Jesus Christ. Do you have a modicum of reading comprehension or are you just here to troll? I literally established at the time that none of us knew what the problem is.

As far as I'm aware, it's been fixed. Yet, somehow, as soon as we think it's fixed, specific individuals like you find a way to break it. Again. Not once, since 1.16, I have had this issue. 

I spent a single line talking about his attitude, since that apparently matters. And he dropped it, and respectfully walked away. And I appreciate that. You on the other hand, don't know how to do that.

Unless you have any information to add to this, please stop filling up our git notifications with nonsense. Thank you, kindly.
