### ISSUE TITLE
[1.21] The Latest verion of the mod request a neoforge version for 1.21.1

### ISSUE THREAD

**Issue by Periam** [quek04/The-Undergarden#197]
After installing the latest version of the mod using curseforge for a modpack built in MC1.21, the mod is requesting the neoforge version for MC 1.21.1

neoforge 21.0.167
jei-1.21-neoforge-19.8.2.99
the_undergarden-1.21.1-0.8.20

![image](https://github.com/user-attachments/assets/b845417f-a62c-45fc-8314-87c286a3dea6)
[crash-2024-08-20_09.23.43-fml.txt](https://github.com/user-attachments/files/16675600/crash-2024-08-20_09.23.43-fml.txt)

**Comment by Fooshcookie** [comment]
The latest update of the Undergarden (the_undergarden-1.21.1-0.8.20), as the name implies, is made for 1.21.1. I would recommend updating to 1.21.1.

**Comment by Periam** [comment]
The mod was installed using Curseforge in a 1.21 modpack. That is why the issue was presented.

**Comment by AmberGoop** [comment]
then that's a problem with the modpack editor, not the mod...?
the mod filename explicitly states it's for 1.21.1
it *will not work* in 1.21

**Comment by Periam** [comment]
That can be or something strange flagged on Curse>?
![image](https://github.com/user-attachments/assets/3789335f-cdf4-4004-9591-cf50c07244ff)

**Comment by AmberGoop** [comment]
that makes more sense, i don't know why it's explicitly labelling the 1.21 version as 1.21.1 as well

**Comment by Fooshcookie** [comment]
I closed this for a reason. 

Downloading a mod pack doesn't care what version something is. It simply tells the client to install things. The author manually installed this in, and didn't test anything after updating.

The problem is whoever made that modpack isn't testing their own pack. Either contact the mod maker, remove the mod or downgrade yourself. You should be on 1.21.1 regardless.
