### ISSUE TITLE
Question about Fabric

### ISSUE THREAD

**Issue by vico93** [quek04/The-Undergarden#202]
Does a Fabric port in the plans?

If not, can other modders interested attempt to port it following the terms of the license (MIT)?

**Comment by AmberGoop** [comment]
there's no plans for an official fabric port, unfortunately i don't recall the team's stance on fans porting it so you're gonna have to wait for an answer from them

**Comment by Fooshcookie** [comment]
No, Fabric nor Quilt are planned for support by the team officially.

As per our license, a port is allowed. I will make a simple term, simply out of respect, that you please keep the mod as is, provide proper credit and communicate development with one of us in the Discord.

This issue is being closed.
